# Generated by Django 5.0.6 on 2024-05-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
