# Generated by Django 5.0.6 on 2024-05-24 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodels',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='imagesmodels',
            index=models.Index(fields=['-total_likes'], name='images_imag_total_l_d9fb95_idx'),
        ),
    ]
